### PR TITLE
Fixed Bug Dropdown moves out of viewport for small screen

### PR DESCRIPTION
**Pull request by GaganSingh5**
## Description
Fix the dropdown overflow issue on small viewports by adding maxHeight property in the  style.css file

## Screenshot of bug and fix

**BUG:** Dropdown going out of viewport

bugtsed

**FIX:** Changed the max-height property

fixed_bugtsed

## Acceptance criteria
- [x]  The dropdown has a limited maxHeight and can be displayed on small screen,
- [x]  The maxHeight is a ratio of the viewPort
- [x]  The dropdown display a scrollbar when content exceeds item size

### CODE REVIEW

**Comment by Romakita** [comment]
Thanks @GaganSingh5 for your help :)

**Comment by GaganSingh5** [comment]
Awesome🎉 @Romakita

**Pull request merged**
