### PR TITLE
chore: Migrate tslint to eslint

### LINKED ISSUE #952: [BUG] tslint is deprecated
## Information

TSLint is deprecated in favor of ESLint https://github.com/palantir/tslint/issues/4534#issue-413722441
- **Version:** 5.65.4
- Packages: 

A few sentences describing the overall goals of the issue.

Migrate to ESLint by replacing `.tslint` with `.eslint`

## Solution

See: 
- https://github.com/TypedProject/tsed-cli/package.json and https://github.com/TypedProject/tsed-cli/
- https://github.com/TypedProject/tsed-cli/blob/master/.eslintrc

## Acceptance criteria

- [ ] Travis CI run linter
- [ ] Linter is executed on commit

### PR DESCRIPTION
**Pull request by akrifari**
## Informations

Type | Breaking change
---|---
Chore | No

****

## Description

This is just raw eslint config which ignored all of those warns and errs. I want to make sure this approach is correct, before I continue further. Let me know if any other change is needed

Close #952

### CODE REVIEW

**Review by Romakita — APPROVED** [review]
Awesome :D
Thanks @akrifari

**Comment by Romakita** [comment]
For me is ok ;). I can merge it if it’s ok for you.

**Comment by akrifari** [comment]
Wait, cleanup little bit. I'll ping you when I'm done

**Comment by Romakita** [comment]
Yes ;)

**Comment by akrifari** [comment]
Please take a look @Romakita

**Review by Romakita — APPROVED** [review]

**Comment by Romakita** [comment]
@akrifari It's ok for me :) Can I merge it?

**Comment by akrifari** [comment]
Sure, go ahead

**Comment by Romakita** [comment]
Merged :) 
Thanks @akrifari

**Pull request merged**
